### ISSUE TITLE
ENH: Support for constellations

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysatSeasons#15]
In `pysat._constellation`, support for the `.add` and `.difference` is being removed for pysat 3.0.0.  `pysatSeasons` already supports constellation objects.  Make sure that the intent of those functions can be replicated here.

**Comment by rstoneback** [comment]
Did the add and difference get pushed over into pysatIncubator?

**Comment by rstoneback** [comment]
Under the general theme of Constellation support, constellation support added to occurrence probability calculations over in #30.
