### ISSUE TITLE
TST: update testing standards

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysatSeasons#28]
**Is your feature request related to a problem? Please describe.**
After the version caps for pandas are removed, CI tests and standards need to be updated.

**Describe the solution you'd like**
- [x] Test against python 3.8 and 3.9
- [ ] Add style and docstring testing
- [x] Update style throughout

**Describe alternatives you've considered**
:crab:

**Additional context**
Needs approval and merge of #27.

**Comment by rstoneback** [comment]
I've updated the test versions. How do I turn on style and docstring testing?

**Comment by rstoneback** [comment]
I added some codes to the flake8 testing based upon comparison to codes in pysat.
```
    - name: Test PEP8 compliance
      run: flake8 . --count --select=D,E,F,H,W --show-source --statistics
```
